server:
  port: 9001
  servlet:
    context-path: /gateway/admin

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: api-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/gateway?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Freemarker
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      servlet:
        content-type: text/html

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.api.gateway
  default-flat-param-object: true


knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: default
    - name: 标题2
      locations: classpath:markdown1/*
      group: 用户模块


gateway:
  user-password-salt: d5ec0a02

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml