server:
  port: 8081
  servlet:
    context-path: /order
#====================================stream =============================================
spring:
  application:
    name: order
  profiles:
    include: datasource,dubbo,seata
    #include: sharding,dubbo,seata
    ##active: 选择哪个配置，多环境配置下使用
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

#====================================mybatis-plus config===============================================
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.order.entity
  configuration:
    map-underscore-to-camel-case: true

#====================================gateway =============================================
api:
  gateway:
    http:
      app-name: order
      version: gray_1.0
      port: 8081
      admin-url: 127.0.0.1:9001/gateway/admin
#====================================nacos =============================================
nacos:
  discovery:
    server-addr: 127.0.0.1:8848



