server:
  port: 9000


nacos:
  discovery:
    server-addr: 127.0.0.1:8848

api:
  gateway:
    load-balance: RANDOM
    time-out-millis: 3000
    cache-refresh-interval: 10
    rate-limit-type: qps
    rate-limit-count: 5